version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:22.9.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Angular Project
          command: npm run build
      - run:
          name: Inject Environment Variables and Modify Index
          command: node inject-env.js
      - persist_to_workspace:
        root: ./dist/envtest/browser
        paths:
          - .
      - store_artifacts:
          path: ./dist
          destination: dist_artifacts
